### ISSUE TITLE
How to set "Card Present" flag use payment method card with device

### ISSUE THREAD

**Issue by zidniilman-08** [fluidpay/fluidpay-js#25]
Hi, i have some trouble to set Card Present flag in transaction.

I have set the the track2 data on the request, but the Card Present flag not set on transaction.
Could you please help me about this

this the data that i send to fluid API
`{
   "payment_method": {
        "card": {
            "entry_type": "swiped",
            "number": "4111111111111111",
            "expiration_date": "12/25",
            "cvc": null,
            "track2": "\u0000*\u0003\u0005';232637226903457778=27052060000000922000?"
        }
    }`

Thanks

**Comment by brianvoe** [comment]
track_2 not track2. Also your track_2 value is invalid.

**Comment by zidniilman-08** [comment]
Alright.

@brianvoe  but why my track_2 data is invalid, what string should i send to fluid ? is it hex string ?

in sample above i just convert track_2 from device to string in nodejs.

Thanks

**Comment by brianvoe** [comment]
https://neapay.com/online-tools/card-track1-track2-generator.html

You can get an idea of the format from that website.

`^;([0-9]{0,19})([=])([0-9]{4})([0-9]+)\?$`

This is the regex we use to validate

**Comment by zidniilman-08** [comment]
Aha, okay i got it now. Thank you

**Comment by zidniilman-08** [comment]
hi @brianvoe 

i'm facing new issue on production when i send track_2 data.
The card was declined when i process the transaction.

`'Card Declined (Do not honor)'`

could you please give me a reason why the card declined ?
fyi, i use mastercard card

example data that i send to fluid
`"payment_method": {
        "card": {
            "entry_type": "swiped",
            "track_2": ";4111111111111111=27112060000000023000?"
        }
    }`
    
    
   Thanks

**Comment by brianvoe** [comment]
what was the reason given in the response?

**Comment by zidniilman-08** [comment]
ahh sorry, i got the reason the card is not honor @brianvoe 

but if i process the transaction with card number (not use track_2), the transaction was success with same card

@brianvoe is the track_2 required the cvc ?

because in another card i get message response like this
`Card Declined (Invalid CVC)`

**Comment by brianvoe** [comment]
So responses like "do not honor" are usually responses back from the processor. So it may be up to them to determine what it required. If you dont have a cvc and submit a swiped card or one with track data. Your issues is that the processor may be saying is, hey do have track data with no cvv, I dont believe your swiped the card, or have the card in your presence, do not honor this card. This is the theory i have.

**Comment by zidniilman-08** [comment]
i see
alright, i think i will try to add a cvc/cvv into track_2

Thanks
